ALTER TABLE model_catalog
    ADD COLUMN deployment TEXT NOT NULL DEFAULT '',
    ADD COLUMN endpoint TEXT NOT NULL DEFAULT '',
    ADD COLUMN api_key TEXT NOT NULL DEFAULT '',
    ADD COLUMN api_version TEXT NOT NULL DEFAULT '',
    ADD COLUMN region TEXT NOT NULL DEFAULT '',
    ADD COLUMN metadata_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN weight INT NOT NULL DEFAULT 100;
