-- +goose Up
ALTER TABLE batches ADD COLUMN IF NOT EXISTS in_progress_at TIMESTAMPTZ;
ALTER TABLE batches ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE batches ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;
ALTER TABLE batches ADD COLUMN IF NOT EXISTS finalizing_at TIMESTAMPTZ;
ALTER TABLE batches ADD COLUMN IF NOT EXISTS failed_at TIMESTAMPTZ;
ALTER TABLE batches ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

-- +goose Down
ALTER TABLE batches DROP COLUMN IF EXISTS expires_at;
ALTER TABLE batches DROP COLUMN IF EXISTS failed_at;
ALTER TABLE batches DROP COLUMN IF EXISTS finalizing_at;
ALTER TABLE batches DROP COLUMN IF EXISTS cancelled_at;
ALTER TABLE batches DROP COLUMN IF EXISTS completed_at;
ALTER TABLE batches DROP COLUMN IF EXISTS in_progress_at;
