// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminAPIKey = `-- name: CreateAdminAPIKey :one
INSERT INTO admin_api_keys (
    name,
    prefix,
    secret_hash,
    scope,
    owner_user_id,
    created_by_user_id,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, prefix, secret_hash, scope, owner_user_id, created_by_user_id, expires_at, revoked_at, last_used_at, created_at
`

type CreateAdminAPIKeyParams struct {
	Name            string             `json:"name"`
	Prefix          string             `json:"prefix"`
	SecretHash      string             `json:"secret_hash"`
	Scope           AdminApiKeyScope   `json:"scope"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAdminAPIKey(ctx context.Context, arg CreateAdminAPIKeyParams) (AdminApiKey, error) {
	row := q.db.QueryRow(ctx, createAdminAPIKey,
		arg.Name,
		arg.Prefix,
		arg.SecretHash,
		arg.Scope,
		arg.OwnerUserID,
		arg.CreatedByUserID,
		arg.ExpiresAt,
	)
	var i AdminApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scope,
		&i.OwnerUserID,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminAPIKeyByID = `-- name: GetAdminAPIKeyByID :one
SELECT id, name, prefix, secret_hash, scope, owner_user_id, created_by_user_id, expires_at, revoked_at, last_used_at, created_at
FROM admin_api_keys
WHERE id = $1
`

func (q *Queries) GetAdminAPIKeyByID(ctx context.Context, id pgtype.UUID) (AdminApiKey, error) {
	row := q.db.QueryRow(ctx, getAdminAPIKeyByID, id)
	var i AdminApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scope,
		&i.OwnerUserID,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminAPIKeyByPrefix = `-- name: GetAdminAPIKeyByPrefix :one
SELECT id, name, prefix, secret_hash, scope, owner_user_id, created_by_user_id, expires_at, revoked_at, last_used_at, created_at
FROM admin_api_keys
WHERE prefix = $1
`

func (q *Queries) GetAdminAPIKeyByPrefix(ctx context.Context, prefix string) (AdminApiKey, error) {
	row := q.db.QueryRow(ctx, getAdminAPIKeyByPrefix, prefix)
	var i AdminApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scope,
		&i.OwnerUserID,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminAPIKeys = `-- name: ListAdminAPIKeys :many
SELECT
    k.id,
    k.name,
    k.prefix,
    k.secret_hash,
    k.scope,
    k.owner_user_id,
    k.created_by_user_id,
    k.expires_at,
    k.revoked_at,
    k.last_used_at,
    k.created_at,
    owner.email AS owner_email,
    owner.name AS owner_name,
    creator.email AS creator_email,
    creator.name AS creator_name
FROM admin_api_keys k
LEFT JOIN users owner ON owner.id = k.owner_user_id
JOIN users creator ON creator.id = k.created_by_user_id
ORDER BY k.created_at DESC
`

type ListAdminAPIKeysRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Prefix          string             `json:"prefix"`
	SecretHash      string             `json:"secret_hash"`
	Scope           AdminApiKeyScope   `json:"scope"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	OwnerEmail      pgtype.Text        `json:"owner_email"`
	OwnerName       pgtype.Text        `json:"owner_name"`
	CreatorEmail    string             `json:"creator_email"`
	CreatorName     string             `json:"creator_name"`
}

func (q *Queries) ListAdminAPIKeys(ctx context.Context) ([]ListAdminAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAdminAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAPIKeysRow{}
	for rows.Next() {
		var i ListAdminAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.SecretHash,
			&i.Scope,
			&i.OwnerUserID,
			&i.CreatedByUserID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.OwnerEmail,
			&i.OwnerName,
			&i.CreatorEmail,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminAPIKeysByOwner = `-- name: ListAdminAPIKeysByOwner :many
SELECT
    k.id,
    k.name,
    k.prefix,
    k.secret_hash,
    k.scope,
    k.owner_user_id,
    k.created_by_user_id,
    k.expires_at,
    k.revoked_at,
    k.last_used_at,
    k.created_at,
    owner.email AS owner_email,
    owner.name AS owner_name,
    creator.email AS creator_email,
    creator.name AS creator_name
FROM admin_api_keys k
LEFT JOIN users owner ON owner.id = k.owner_user_id
JOIN users creator ON creator.id = k.created_by_user_id
WHERE k.owner_user_id = $1
ORDER BY k.created_at DESC
`

type ListAdminAPIKeysByOwnerRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Prefix          string             `json:"prefix"`
	SecretHash      string             `json:"secret_hash"`
	Scope           AdminApiKeyScope   `json:"scope"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	OwnerEmail      pgtype.Text        `json:"owner_email"`
	OwnerName       pgtype.Text        `json:"owner_name"`
	CreatorEmail    string             `json:"creator_email"`
	CreatorName     string             `json:"creator_name"`
}

func (q *Queries) ListAdminAPIKeysByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]ListAdminAPIKeysByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listAdminAPIKeysByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAPIKeysByOwnerRow{}
	for rows.Next() {
		var i ListAdminAPIKeysByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.SecretHash,
			&i.Scope,
			&i.OwnerUserID,
			&i.CreatedByUserID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.OwnerEmail,
			&i.OwnerName,
			&i.CreatorEmail,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdminAPIKey = `-- name: RevokeAdminAPIKey :one
UPDATE admin_api_keys
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, name, prefix, secret_hash, scope, owner_user_id, created_by_user_id, expires_at, revoked_at, last_used_at, created_at
`

func (q *Queries) RevokeAdminAPIKey(ctx context.Context, id pgtype.UUID) (AdminApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAdminAPIKey, id)
	var i AdminApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scope,
		&i.OwnerUserID,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAdminAPIKeyLastUsed = `-- name: UpdateAdminAPIKeyLastUsed :exec
UPDATE admin_api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAdminAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAdminAPIKeyLastUsed, id)
	return err
}
