// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key_rate_limits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAPIKeyRateLimit = `-- name: DeleteAPIKeyRateLimit :execrows
DELETE FROM api_key_rate_limits
WHERE api_key_id = $1
`

func (q *Queries) DeleteAPIKeyRateLimit(ctx context.Context, apiKeyID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKeyRateLimit, apiKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyRateLimit = `-- name: GetAPIKeyRateLimit :one
SELECT api_key_id,
       requests_per_minute,
       tokens_per_minute,
       parallel_requests
FROM api_key_rate_limits
WHERE api_key_id = $1
`

type GetAPIKeyRateLimitRow struct {
	ApiKeyID          pgtype.UUID `json:"api_key_id"`
	RequestsPerMinute int32       `json:"requests_per_minute"`
	TokensPerMinute   int32       `json:"tokens_per_minute"`
	ParallelRequests  int32       `json:"parallel_requests"`
}

func (q *Queries) GetAPIKeyRateLimit(ctx context.Context, apiKeyID pgtype.UUID) (GetAPIKeyRateLimitRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyRateLimit, apiKeyID)
	var i GetAPIKeyRateLimitRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.RequestsPerMinute,
		&i.TokensPerMinute,
		&i.ParallelRequests,
	)
	return i, err
}

const listAPIKeyRateLimits = `-- name: ListAPIKeyRateLimits :many
SELECT ak.prefix AS prefix,
       r.api_key_id,
       r.requests_per_minute,
       r.tokens_per_minute,
       r.parallel_requests
FROM api_key_rate_limits r
JOIN api_keys ak ON ak.id = r.api_key_id
`

type ListAPIKeyRateLimitsRow struct {
	Prefix            string      `json:"prefix"`
	ApiKeyID          pgtype.UUID `json:"api_key_id"`
	RequestsPerMinute int32       `json:"requests_per_minute"`
	TokensPerMinute   int32       `json:"tokens_per_minute"`
	ParallelRequests  int32       `json:"parallel_requests"`
}

func (q *Queries) ListAPIKeyRateLimits(ctx context.Context) ([]ListAPIKeyRateLimitsRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeyRateLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeyRateLimitsRow{}
	for rows.Next() {
		var i ListAPIKeyRateLimitsRow
		if err := rows.Scan(
			&i.Prefix,
			&i.ApiKeyID,
			&i.RequestsPerMinute,
			&i.TokensPerMinute,
			&i.ParallelRequests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAPIKeyRateLimit = `-- name: UpsertAPIKeyRateLimit :one
INSERT INTO api_key_rate_limits (
    api_key_id,
    requests_per_minute,
    tokens_per_minute,
    parallel_requests
) VALUES ($1, $2, $3, $4)
ON CONFLICT (api_key_id) DO UPDATE
SET requests_per_minute = EXCLUDED.requests_per_minute,
    tokens_per_minute = EXCLUDED.tokens_per_minute,
    parallel_requests = EXCLUDED.parallel_requests,
    updated_at = NOW()
RETURNING api_key_id,
          requests_per_minute,
          tokens_per_minute,
          parallel_requests
`

type UpsertAPIKeyRateLimitParams struct {
	ApiKeyID          pgtype.UUID `json:"api_key_id"`
	RequestsPerMinute int32       `json:"requests_per_minute"`
	TokensPerMinute   int32       `json:"tokens_per_minute"`
	ParallelRequests  int32       `json:"parallel_requests"`
}

type UpsertAPIKeyRateLimitRow struct {
	ApiKeyID          pgtype.UUID `json:"api_key_id"`
	RequestsPerMinute int32       `json:"requests_per_minute"`
	TokensPerMinute   int32       `json:"tokens_per_minute"`
	ParallelRequests  int32       `json:"parallel_requests"`
}

func (q *Queries) UpsertAPIKeyRateLimit(ctx context.Context, arg UpsertAPIKeyRateLimitParams) (UpsertAPIKeyRateLimitRow, error) {
	row := q.db.QueryRow(ctx, upsertAPIKeyRateLimit,
		arg.ApiKeyID,
		arg.RequestsPerMinute,
		arg.TokensPerMinute,
		arg.ParallelRequests,
	)
	var i UpsertAPIKeyRateLimitRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.RequestsPerMinute,
		&i.TokensPerMinute,
		&i.ParallelRequests,
	)
	return i, err
}
