// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO admin_audit_logs (
    user_id,
    action,
    resource_type,
    resource_id,
    metadata
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, action, resource_type, resource_id, metadata, created_at
`

type InsertAuditLogParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   string      `json:"resource_id"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, resource_type, resource_id, metadata, created_at
FROM admin_audit_logs
WHERE (
    $1::uuid IS NULL
    OR user_id = $1::uuid
)
  AND (
    $2::text IS NULL
    OR action = $2::text
)
  AND (
    $3::text IS NULL
    OR resource_type = $3::text
)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListAuditLogsParams struct {
	UserIDFilter   pgtype.UUID `json:"user_id_filter"`
	ActionFilter   pgtype.Text `json:"action_filter"`
	ResourceFilter pgtype.Text `json:"resource_filter"`
	ListOffset     int32       `json:"list_offset"`
	ListLimit      int32       `json:"list_limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.UserIDFilter,
		arg.ActionFilter,
		arg.ResourceFilter,
		arg.ListOffset,
		arg.ListLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
