// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBillingWebhook = `-- name: CreateBillingWebhook :one
INSERT INTO billing_webhooks (
    tenant_id,
    name,
    url,
    secret,
    enabled
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, url, secret, enabled, created_at, updated_at
`

type CreateBillingWebhookParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     pgtype.Text `json:"name"`
	Url      string      `json:"url"`
	Secret   pgtype.Text `json:"secret"`
	Enabled  bool        `json:"enabled"`
}

func (q *Queries) CreateBillingWebhook(ctx context.Context, arg CreateBillingWebhookParams) (BillingWebhook, error) {
	row := q.db.QueryRow(ctx, createBillingWebhook,
		arg.TenantID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Enabled,
	)
	var i BillingWebhook
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBillingWebhook = `-- name: DeleteBillingWebhook :exec
DELETE FROM billing_webhooks
WHERE id = $1
`

func (q *Queries) DeleteBillingWebhook(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBillingWebhook, id)
	return err
}

const getBillingWebhook = `-- name: GetBillingWebhook :one
SELECT id, tenant_id, name, url, secret, enabled, created_at, updated_at
FROM billing_webhooks
WHERE id = $1
`

func (q *Queries) GetBillingWebhook(ctx context.Context, id pgtype.UUID) (BillingWebhook, error) {
	row := q.db.QueryRow(ctx, getBillingWebhook, id)
	var i BillingWebhook
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingWebhookEvent = `-- name: GetBillingWebhookEvent :one
SELECT id, webhook_id, tenant_id, period_start, period_end, payload, success, status_code, error, created_at
FROM billing_webhook_events
WHERE id = $1
`

func (q *Queries) GetBillingWebhookEvent(ctx context.Context, id pgtype.UUID) (BillingWebhookEvent, error) {
	row := q.db.QueryRow(ctx, getBillingWebhookEvent, id)
	var i BillingWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Payload,
		&i.Success,
		&i.StatusCode,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const insertBillingWebhookEvent = `-- name: InsertBillingWebhookEvent :one
INSERT INTO billing_webhook_events (
    webhook_id,
    tenant_id,
    period_start,
    period_end,
    payload,
    success,
    status_code,
    error
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, webhook_id, tenant_id, period_start, period_end, payload, success, status_code, error, created_at
`

type InsertBillingWebhookEventParams struct {
	WebhookID   pgtype.UUID        `json:"webhook_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	Payload     []byte             `json:"payload"`
	Success     bool               `json:"success"`
	StatusCode  pgtype.Int4        `json:"status_code"`
	Error       pgtype.Text        `json:"error"`
}

func (q *Queries) InsertBillingWebhookEvent(ctx context.Context, arg InsertBillingWebhookEventParams) (BillingWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertBillingWebhookEvent,
		arg.WebhookID,
		arg.TenantID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Payload,
		arg.Success,
		arg.StatusCode,
		arg.Error,
	)
	var i BillingWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.TenantID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Payload,
		&i.Success,
		&i.StatusCode,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listBillingWebhookEvents = `-- name: ListBillingWebhookEvents :many
SELECT id, webhook_id, tenant_id, period_start, period_end, payload, success, status_code, error, created_at
FROM billing_webhook_events
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBillingWebhookEventsParams struct {
	WebhookID pgtype.UUID `json:"webhook_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListBillingWebhookEvents(ctx context.Context, arg ListBillingWebhookEventsParams) ([]BillingWebhookEvent, error) {
	rows, err := q.db.Query(ctx, listBillingWebhookEvents, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingWebhookEvent{}
	for rows.Next() {
		var i BillingWebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.TenantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Payload,
			&i.Success,
			&i.StatusCode,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingWebhooksAdmin = `-- name: ListBillingWebhooksAdmin :many
SELECT id, tenant_id, name, url, secret, enabled, created_at, updated_at
FROM billing_webhooks
ORDER BY created_at DESC
`

func (q *Queries) ListBillingWebhooksAdmin(ctx context.Context) ([]BillingWebhook, error) {
	rows, err := q.db.Query(ctx, listBillingWebhooksAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingWebhook{}
	for rows.Next() {
		var i BillingWebhook
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingWebhooksByTenant = `-- name: ListBillingWebhooksByTenant :many
SELECT id, tenant_id, name, url, secret, enabled, created_at, updated_at
FROM billing_webhooks
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBillingWebhooksByTenant(ctx context.Context, tenantID pgtype.UUID) ([]BillingWebhook, error) {
	rows, err := q.db.Query(ctx, listBillingWebhooksByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingWebhook{}
	for rows.Next() {
		var i BillingWebhook
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBillingWebhook = `-- name: UpdateBillingWebhook :one
UPDATE billing_webhooks
SET name = $2,
    url = $3,
    secret = $4,
    enabled = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, name, url, secret, enabled, created_at, updated_at
`

type UpdateBillingWebhookParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    pgtype.Text `json:"name"`
	Url     string      `json:"url"`
	Secret  pgtype.Text `json:"secret"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpdateBillingWebhook(ctx context.Context, arg UpdateBillingWebhookParams) (BillingWebhook, error) {
	row := q.db.QueryRow(ctx, updateBillingWebhook,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Enabled,
	)
	var i BillingWebhook
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
