// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

const deleteTenantBudgetOverride = `-- name: DeleteTenantBudgetOverride :exec
DELETE FROM tenant_budget_overrides
WHERE tenant_id = $1
`

func (q *Queries) DeleteTenantBudgetOverride(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantBudgetOverride, tenantID)
	return err
}

const getBudgetDefaults = `-- name: GetBudgetDefaults :one
SELECT id,
       default_usd,
       warning_threshold,
       refresh_schedule,
       alert_emails,
       alert_webhooks,
       alert_cooldown_seconds,
       created_at,
       created_by_user_id,
       updated_at,
       updated_by_user_id
FROM budget_defaults
WHERE id = TRUE
`

func (q *Queries) GetBudgetDefaults(ctx context.Context) (BudgetDefault, error) {
	row := q.db.QueryRow(ctx, getBudgetDefaults)
	var i BudgetDefault
	err := row.Scan(
		&i.ID,
		&i.DefaultUsd,
		&i.WarningThreshold,
		&i.RefreshSchedule,
		&i.AlertEmails,
		&i.AlertWebhooks,
		&i.AlertCooldownSeconds,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const getTenantBudgetOverride = `-- name: GetTenantBudgetOverride :one
SELECT tenant_id,
       budget_usd,
       warning_threshold,
       refresh_schedule,
       alert_emails,
       alert_webhooks,
       alert_cooldown_seconds,
       last_alert_at,
       last_alert_level,
       created_at,
       updated_at
FROM tenant_budget_overrides
WHERE tenant_id = $1
`

func (q *Queries) GetTenantBudgetOverride(ctx context.Context, tenantID pgtype.UUID) (TenantBudgetOverride, error) {
	row := q.db.QueryRow(ctx, getTenantBudgetOverride, tenantID)
	var i TenantBudgetOverride
	err := row.Scan(
		&i.TenantID,
		&i.BudgetUsd,
		&i.WarningThreshold,
		&i.RefreshSchedule,
		&i.AlertEmails,
		&i.AlertWebhooks,
		&i.AlertCooldownSeconds,
		&i.LastAlertAt,
		&i.LastAlertLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBudgetAlertEvent = `-- name: InsertBudgetAlertEvent :exec
INSERT INTO budget_alert_events (
    tenant_id,
    level,
    channels,
    payload,
    success,
    error
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBudgetAlertEventParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Level    string      `json:"level"`
	Channels []byte      `json:"channels"`
	Payload  []byte      `json:"payload"`
	Success  bool        `json:"success"`
	Error    pgtype.Text `json:"error"`
}

func (q *Queries) InsertBudgetAlertEvent(ctx context.Context, arg InsertBudgetAlertEventParams) error {
	_, err := q.db.Exec(ctx, insertBudgetAlertEvent,
		arg.TenantID,
		arg.Level,
		arg.Channels,
		arg.Payload,
		arg.Success,
		arg.Error,
	)
	return err
}

const listTenantBudgetOverrides = `-- name: ListTenantBudgetOverrides :many
SELECT tenant_id,
       budget_usd,
       warning_threshold,
       refresh_schedule,
       alert_emails,
       alert_webhooks,
       alert_cooldown_seconds,
       last_alert_at,
       last_alert_level,
       created_at,
       updated_at
FROM tenant_budget_overrides
ORDER BY created_at DESC
`

func (q *Queries) ListTenantBudgetOverrides(ctx context.Context) ([]TenantBudgetOverride, error) {
	rows, err := q.db.Query(ctx, listTenantBudgetOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantBudgetOverride{}
	for rows.Next() {
		var i TenantBudgetOverride
		if err := rows.Scan(
			&i.TenantID,
			&i.BudgetUsd,
			&i.WarningThreshold,
			&i.RefreshSchedule,
			&i.AlertEmails,
			&i.AlertWebhooks,
			&i.AlertCooldownSeconds,
			&i.LastAlertAt,
			&i.LastAlertLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantBudgetAlertState = `-- name: UpdateTenantBudgetAlertState :exec
UPDATE tenant_budget_overrides
SET last_alert_at = $2,
    last_alert_level = $3,
    updated_at = NOW()
WHERE tenant_id = $1
`

type UpdateTenantBudgetAlertStateParams struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	LastAlertAt    pgtype.Timestamptz `json:"last_alert_at"`
	LastAlertLevel pgtype.Text        `json:"last_alert_level"`
}

func (q *Queries) UpdateTenantBudgetAlertState(ctx context.Context, arg UpdateTenantBudgetAlertStateParams) error {
	_, err := q.db.Exec(ctx, updateTenantBudgetAlertState, arg.TenantID, arg.LastAlertAt, arg.LastAlertLevel)
	return err
}

const upsertBudgetDefaults = `-- name: UpsertBudgetDefaults :one
INSERT INTO budget_defaults (
    id,
    default_usd,
    warning_threshold,
    refresh_schedule,
    alert_emails,
    alert_webhooks,
    alert_cooldown_seconds,
    created_by_user_id,
    updated_by_user_id
)
VALUES (TRUE, $1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET default_usd = EXCLUDED.default_usd,
    warning_threshold = EXCLUDED.warning_threshold,
    refresh_schedule = EXCLUDED.refresh_schedule,
    alert_emails = EXCLUDED.alert_emails,
    alert_webhooks = EXCLUDED.alert_webhooks,
    alert_cooldown_seconds = EXCLUDED.alert_cooldown_seconds,
    updated_at = NOW(),
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    created_by_user_id = COALESCE(budget_defaults.created_by_user_id, EXCLUDED.created_by_user_id)
RETURNING id,
          default_usd,
          warning_threshold,
          refresh_schedule,
          alert_emails,
          alert_webhooks,
          alert_cooldown_seconds,
          created_at,
          created_by_user_id,
          updated_at,
          updated_by_user_id
`

type UpsertBudgetDefaultsParams struct {
	DefaultUsd           decimal.Decimal `json:"default_usd"`
	WarningThreshold     decimal.Decimal `json:"warning_threshold"`
	RefreshSchedule      string          `json:"refresh_schedule"`
	AlertEmails          []string        `json:"alert_emails"`
	AlertWebhooks        []string        `json:"alert_webhooks"`
	AlertCooldownSeconds int32           `json:"alert_cooldown_seconds"`
	CreatedByUserID      pgtype.UUID     `json:"created_by_user_id"`
	UpdatedByUserID      pgtype.UUID     `json:"updated_by_user_id"`
}

func (q *Queries) UpsertBudgetDefaults(ctx context.Context, arg UpsertBudgetDefaultsParams) (BudgetDefault, error) {
	row := q.db.QueryRow(ctx, upsertBudgetDefaults,
		arg.DefaultUsd,
		arg.WarningThreshold,
		arg.RefreshSchedule,
		arg.AlertEmails,
		arg.AlertWebhooks,
		arg.AlertCooldownSeconds,
		arg.CreatedByUserID,
		arg.UpdatedByUserID,
	)
	var i BudgetDefault
	err := row.Scan(
		&i.ID,
		&i.DefaultUsd,
		&i.WarningThreshold,
		&i.RefreshSchedule,
		&i.AlertEmails,
		&i.AlertWebhooks,
		&i.AlertCooldownSeconds,
		&i.CreatedAt,
		&i.CreatedByUserID,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
	)
	return i, err
}

const upsertTenantBudgetOverride = `-- name: UpsertTenantBudgetOverride :one
INSERT INTO tenant_budget_overrides (
    tenant_id,
    budget_usd,
    warning_threshold,
    refresh_schedule,
    alert_emails,
    alert_webhooks,
    alert_cooldown_seconds
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id) DO UPDATE
SET budget_usd = EXCLUDED.budget_usd,
    warning_threshold = EXCLUDED.warning_threshold,
    refresh_schedule = EXCLUDED.refresh_schedule,
    alert_emails = EXCLUDED.alert_emails,
    alert_webhooks = EXCLUDED.alert_webhooks,
    alert_cooldown_seconds = EXCLUDED.alert_cooldown_seconds,
    updated_at = NOW()
RETURNING tenant_id,
          budget_usd,
          warning_threshold,
          refresh_schedule,
          alert_emails,
          alert_webhooks,
          alert_cooldown_seconds,
          last_alert_at,
          last_alert_level,
          created_at,
          updated_at
`

type UpsertTenantBudgetOverrideParams struct {
	TenantID             pgtype.UUID     `json:"tenant_id"`
	BudgetUsd            decimal.Decimal `json:"budget_usd"`
	WarningThreshold     decimal.Decimal `json:"warning_threshold"`
	RefreshSchedule      string          `json:"refresh_schedule"`
	AlertEmails          []string        `json:"alert_emails"`
	AlertWebhooks        []string        `json:"alert_webhooks"`
	AlertCooldownSeconds int32           `json:"alert_cooldown_seconds"`
}

func (q *Queries) UpsertTenantBudgetOverride(ctx context.Context, arg UpsertTenantBudgetOverrideParams) (TenantBudgetOverride, error) {
	row := q.db.QueryRow(ctx, upsertTenantBudgetOverride,
		arg.TenantID,
		arg.BudgetUsd,
		arg.WarningThreshold,
		arg.RefreshSchedule,
		arg.AlertEmails,
		arg.AlertWebhooks,
		arg.AlertCooldownSeconds,
	)
	var i TenantBudgetOverride
	err := row.Scan(
		&i.TenantID,
		&i.BudgetUsd,
		&i.WarningThreshold,
		&i.RefreshSchedule,
		&i.AlertEmails,
		&i.AlertWebhooks,
		&i.AlertCooldownSeconds,
		&i.LastAlertAt,
		&i.LastAlertLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
