// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: default_models.sql

package db

import (
	"context"
)

const deleteDefaultModel = `-- name: DeleteDefaultModel :exec
DELETE FROM default_models
WHERE alias = $1
`

func (q *Queries) DeleteDefaultModel(ctx context.Context, alias string) error {
	_, err := q.db.Exec(ctx, deleteDefaultModel, alias)
	return err
}

const listDefaultModels = `-- name: ListDefaultModels :many
SELECT alias
FROM default_models
ORDER BY alias
`

func (q *Queries) ListDefaultModels(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDefaultModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var alias string
		if err := rows.Scan(&alias); err != nil {
			return nil, err
		}
		items = append(items, alias)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDefaultModel = `-- name: UpsertDefaultModel :exec
INSERT INTO default_models (alias)
VALUES ($1)
ON CONFLICT (alias) DO NOTHING
`

func (q *Queries) UpsertDefaultModel(ctx context.Context, alias string) error {
	_, err := q.db.Exec(ctx, upsertDefaultModel, alias)
	return err
}
