// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTenantMembership = `-- name: AddTenantMembership :one
INSERT INTO tenant_memberships (tenant_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, user_id, role, created_at
`

type AddTenantMembershipParams struct {
	TenantID pgtype.UUID    `json:"tenant_id"`
	UserID   pgtype.UUID    `json:"user_id"`
	Role     MembershipRole `json:"role"`
}

func (q *Queries) AddTenantMembership(ctx context.Context, arg AddTenantMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, addTenantMembership, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMembership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantMembership = `-- name: GetTenantMembership :one
SELECT id, tenant_id, user_id, role, created_at
FROM tenant_memberships
WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantMembershipParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTenantMembership(ctx context.Context, arg GetTenantMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, getTenantMembership, arg.TenantID, arg.UserID)
	var i TenantMembership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT
    tm.id,
    tm.tenant_id,
    tm.user_id,
    tm.role,
    tm.created_at,
    u.email AS user_email,
    u.name AS user_name,
    u.created_at AS user_created_at
FROM tenant_memberships tm
JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = $1
ORDER BY u.email
`

type ListTenantMembersRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Role          MembershipRole     `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UserEmail     string             `json:"user_email"`
	UserName      string             `json:"user_name"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) ListTenantMembers(ctx context.Context, tenantID pgtype.UUID) ([]ListTenantMembersRow, error) {
	rows, err := q.db.Query(ctx, listTenantMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantMembersRow{}
	for rows.Next() {
		var i ListTenantMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
			&i.UserCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTenants = `-- name: ListUserTenants :many
SELECT
    tm.id,
    tm.tenant_id,
    tm.user_id,
    tm.role,
    tm.created_at,
    t.name AS tenant_name,
    t.status AS tenant_status,
    t.created_at AS tenant_created_at
FROM tenant_memberships tm
JOIN tenants t ON t.id = tm.tenant_id
WHERE tm.user_id = $1
ORDER BY t.name
`

type ListUserTenantsRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Role            MembershipRole     `json:"role"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TenantName      string             `json:"tenant_name"`
	TenantStatus    TenantStatus       `json:"tenant_status"`
	TenantCreatedAt pgtype.Timestamptz `json:"tenant_created_at"`
}

func (q *Queries) ListUserTenants(ctx context.Context, userID pgtype.UUID) ([]ListUserTenantsRow, error) {
	rows, err := q.db.Query(ctx, listUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTenantsRow{}
	for rows.Next() {
		var i ListUserTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.TenantName,
			&i.TenantStatus,
			&i.TenantCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTenantMembership = `-- name: RemoveTenantMembership :exec
DELETE FROM tenant_memberships
WHERE tenant_id = $1 AND user_id = $2
`

type RemoveTenantMembershipParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTenantMembership(ctx context.Context, arg RemoveTenantMembershipParams) error {
	_, err := q.db.Exec(ctx, removeTenantMembership, arg.TenantID, arg.UserID)
	return err
}

const updateTenantMembershipRole = `-- name: UpdateTenantMembershipRole :one
UPDATE tenant_memberships
SET role = $3
WHERE tenant_id = $1 AND user_id = $2
RETURNING id, tenant_id, user_id, role, created_at
`

type UpdateTenantMembershipRoleParams struct {
	TenantID pgtype.UUID    `json:"tenant_id"`
	UserID   pgtype.UUID    `json:"user_id"`
	Role     MembershipRole `json:"role"`
}

func (q *Queries) UpdateTenantMembershipRole(ctx context.Context, arg UpdateTenantMembershipRoleParams) (TenantMembership, error) {
	row := q.db.QueryRow(ctx, updateTenantMembershipRole, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMembership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
