// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

type ApiKeyKind string

const (
	ApiKeyKindService  ApiKeyKind = "service"
	ApiKeyKindPersonal ApiKeyKind = "personal"
)

func (e *ApiKeyKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApiKeyKind(s)
	case string:
		*e = ApiKeyKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ApiKeyKind: %T", src)
	}
	return nil
}

type NullApiKeyKind struct {
	ApiKeyKind ApiKeyKind `json:"api_key_kind"`
	Valid      bool       `json:"valid"` // Valid is true if ApiKeyKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApiKeyKind) Scan(value interface{}) error {
	if value == nil {
		ns.ApiKeyKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApiKeyKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApiKeyKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApiKeyKind), nil
}

type MembershipRole string

const (
	MembershipRoleOwner  MembershipRole = "owner"
	MembershipRoleAdmin  MembershipRole = "admin"
	MembershipRoleViewer MembershipRole = "viewer"
	MembershipRoleUser   MembershipRole = "user"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type TenantKind string

const (
	TenantKindOrganization TenantKind = "organization"
	TenantKindPersonal     TenantKind = "personal"
)

func (e *TenantKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantKind(s)
	case string:
		*e = TenantKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantKind: %T", src)
	}
	return nil
}

type NullTenantKind struct {
	TenantKind TenantKind `json:"tenant_kind"`
	Valid      bool       `json:"valid"` // Valid is true if TenantKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantKind) Scan(value interface{}) error {
	if value == nil {
		ns.TenantKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantKind), nil
}

type TenantStatus string

const (
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type AdminAuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Prefix      string             `json:"prefix"`
	SecretHash  string             `json:"secret_hash"`
	Name        string             `json:"name"`
	ScopesJson  []byte             `json:"scopes_json"`
	QuotaJson   []byte             `json:"quota_json"`
	Kind        ApiKeyKind         `json:"kind"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}

type Batch struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	ApiKeyID              pgtype.UUID        `json:"api_key_id"`
	Status                string             `json:"status"`
	Endpoint              string             `json:"endpoint"`
	InputFileID           pgtype.UUID        `json:"input_file_id"`
	ResultFileID          pgtype.UUID        `json:"result_file_id"`
	ErrorFileID           pgtype.UUID        `json:"error_file_id"`
	CompletionWindow      pgtype.Text        `json:"completion_window"`
	MaxConcurrency        int32              `json:"max_concurrency"`
	Metadata              []byte             `json:"metadata"`
	RequestCountTotal     int32              `json:"request_count_total"`
	RequestCountCompleted int32              `json:"request_count_completed"`
	RequestCountFailed    int32              `json:"request_count_failed"`
	RequestCountCancelled int32              `json:"request_count_cancelled"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	InProgressAt          pgtype.Timestamptz `json:"in_progress_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	CancelledAt           pgtype.Timestamptz `json:"cancelled_at"`
	FinalizingAt          pgtype.Timestamptz `json:"finalizing_at"`
	FailedAt              pgtype.Timestamptz `json:"failed_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

type BatchItem struct {
	ID          pgtype.UUID        `json:"id"`
	BatchID     pgtype.UUID        `json:"batch_id"`
	ItemIndex   int64              `json:"item_index"`
	Status      string             `json:"status"`
	CustomID    pgtype.Text        `json:"custom_id"`
	Input       []byte             `json:"input"`
	Response    []byte             `json:"response"`
	Error       []byte             `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type BudgetAlertEvent struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Level     string             `json:"level"`
	Channels  []byte             `json:"channels"`
	Payload   []byte             `json:"payload"`
	Success   bool               `json:"success"`
	Error     pgtype.Text        `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BudgetDefault struct {
	ID                   bool               `json:"id"`
	DefaultUsd           decimal.Decimal    `json:"default_usd"`
	WarningThreshold     decimal.Decimal    `json:"warning_threshold"`
	RefreshSchedule      string             `json:"refresh_schedule"`
	AlertEmails          []string           `json:"alert_emails"`
	AlertWebhooks        []string           `json:"alert_webhooks"`
	AlertCooldownSeconds int32              `json:"alert_cooldown_seconds"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedByUserID      pgtype.UUID        `json:"created_by_user_id"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	UpdatedByUserID      pgtype.UUID        `json:"updated_by_user_id"`
}

type DefaultModel struct {
	Alias     string             `json:"alias"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Filename       string             `json:"filename"`
	Purpose        string             `json:"purpose"`
	ContentType    string             `json:"content_type"`
	Bytes          int64              `json:"bytes"`
	StorageBackend string             `json:"storage_backend"`
	StorageKey     string             `json:"storage_key"`
	Checksum       pgtype.Text        `json:"checksum"`
	Encrypted      bool               `json:"encrypted"`
	Metadata       []byte             `json:"metadata"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type ModelCatalog struct {
	Alias              string             `json:"alias"`
	Provider           string             `json:"provider"`
	ProviderModel      string             `json:"provider_model"`
	ContextWindow      int32              `json:"context_window"`
	MaxOutputTokens    int32              `json:"max_output_tokens"`
	ModalitiesJson     []byte             `json:"modalities_json"`
	SupportsTools      bool               `json:"supports_tools"`
	PriceInput         decimal.Decimal    `json:"price_input"`
	PriceOutput        decimal.Decimal    `json:"price_output"`
	Currency           string             `json:"currency"`
	Enabled            bool               `json:"enabled"`
	ProviderConfigJson []byte             `json:"provider_config_json"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Deployment         string             `json:"deployment"`
	Endpoint           string             `json:"endpoint"`
	ApiKey             string             `json:"api_key"`
	ApiVersion         string             `json:"api_version"`
	Region             string             `json:"region"`
	MetadataJson       []byte             `json:"metadata_json"`
	Weight             int32              `json:"weight"`
}

type RateLimitDefault struct {
	ID                     bool               `json:"id"`
	RequestsPerMinute      int32              `json:"requests_per_minute"`
	TokensPerMinute        int32              `json:"tokens_per_minute"`
	ParallelRequestsKey    int32              `json:"parallel_requests_key"`
	ParallelRequestsTenant int32              `json:"parallel_requests_tenant"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Request struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ApiKeyID       pgtype.UUID        `json:"api_key_id"`
	Ts             pgtype.Timestamptz `json:"ts"`
	ModelAlias     string             `json:"model_alias"`
	Provider       string             `json:"provider"`
	LatencyMs      int32              `json:"latency_ms"`
	Status         int32              `json:"status"`
	ErrorCode      pgtype.Text        `json:"error_code"`
	InputTokens    int64              `json:"input_tokens"`
	OutputTokens   int64              `json:"output_tokens"`
	CostCents      int64              `json:"cost_cents"`
	CostUsdMicros  int64              `json:"cost_usd_micros"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	TraceID        pgtype.Text        `json:"trace_id"`
}

type Route struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Alias         string             `json:"alias"`
	Provider      string             `json:"provider"`
	ProviderModel string             `json:"provider_model"`
	Weight        int32              `json:"weight"`
	ParamsJson    []byte             `json:"params_json"`
	Region        pgtype.Text        `json:"region"`
	StickyKey     pgtype.Text        `json:"sticky_key"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SystemSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Status    TenantStatus       `json:"status"`
	Kind      TenantKind         `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TenantBudgetOverride struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	BudgetUsd            decimal.Decimal    `json:"budget_usd"`
	WarningThreshold     decimal.Decimal    `json:"warning_threshold"`
	RefreshSchedule      string             `json:"refresh_schedule"`
	AlertEmails          []string           `json:"alert_emails"`
	AlertWebhooks        []string           `json:"alert_webhooks"`
	AlertCooldownSeconds int32              `json:"alert_cooldown_seconds"`
	LastAlertAt          pgtype.Timestamptz `json:"last_alert_at"`
	LastAlertLevel       pgtype.Text        `json:"last_alert_level"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type TenantMembership struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      MembershipRole     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TenantModel struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Alias     string             `json:"alias"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UsageRecord struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ApiKeyID      pgtype.UUID        `json:"api_key_id"`
	Ts            pgtype.Timestamptz `json:"ts"`
	ModelAlias    string             `json:"model_alias"`
	Provider      string             `json:"provider"`
	InputTokens   int64              `json:"input_tokens"`
	OutputTokens  int64              `json:"output_tokens"`
	Requests      int64              `json:"requests"`
	CostCents     int64              `json:"cost_cents"`
	CostUsdMicros int64              `json:"cost_usd_micros"`
}

type User struct {
	ID               pgtype.UUID        `json:"id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	ThemePreference  string             `json:"theme_preference"`
	IsSuperAdmin     bool               `json:"is_super_admin"`
	PersonalTenantID pgtype.UUID        `json:"personal_tenant_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
}

type UserCredential struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	Issuer       string             `json:"issuer"`
	Subject      string             `json:"subject"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
