// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_incidents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProviderIncidents = `-- name: CountProviderIncidents :one
SELECT count(*) FROM provider_incidents
WHERE ($1::text = '' OR provider = $1::text)
  AND ($2::text = '' OR model_alias = $2::text)
  AND ($3::text = '' OR status = $3::text)
`

type CountProviderIncidentsParams struct {
	Provider   string `json:"provider"`
	ModelAlias string `json:"model_alias"`
	Status     string `json:"status"`
}

func (q *Queries) CountProviderIncidents(ctx context.Context, arg CountProviderIncidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderIncidents, arg.Provider, arg.ModelAlias, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProviderIncidents = `-- name: ListProviderIncidents :many
SELECT id, provider, model_alias, incident_type, status, window_seconds, opened_at, resolved_at, window_started_at, window_ended_at, sample_error, request_count, error_count, timeout_count, latency_p95_ms, metadata
FROM provider_incidents
WHERE ($1::text = '' OR provider = $1::text)
  AND ($2::text = '' OR model_alias = $2::text)
  AND ($3::text = '' OR status = $3::text)
ORDER BY opened_at DESC
LIMIT $5 OFFSET $4
`

type ListProviderIncidentsParams struct {
	Provider   string `json:"provider"`
	ModelAlias string `json:"model_alias"`
	Status     string `json:"status"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListProviderIncidents(ctx context.Context, arg ListProviderIncidentsParams) ([]ProviderIncident, error) {
	rows, err := q.db.Query(ctx, listProviderIncidents,
		arg.Provider,
		arg.ModelAlias,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderIncident{}
	for rows.Next() {
		var i ProviderIncident
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelAlias,
			&i.IncidentType,
			&i.Status,
			&i.WindowSeconds,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.WindowStartedAt,
			&i.WindowEndedAt,
			&i.SampleError,
			&i.RequestCount,
			&i.ErrorCount,
			&i.TimeoutCount,
			&i.LatencyP95Ms,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeProviderIncidents = `-- name: PurgeProviderIncidents :exec
DELETE FROM provider_incidents
WHERE opened_at < NOW() - ($1 * INTERVAL '1 day')
`

func (q *Queries) PurgeProviderIncidents(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.Exec(ctx, purgeProviderIncidents, dollar_1)
	return err
}

const resolveProviderIncident = `-- name: ResolveProviderIncident :one
UPDATE provider_incidents
SET status = 'resolved',
    resolved_at = NOW(),
    metadata = COALESCE($4, metadata)
WHERE provider = $1 AND model_alias = $2 AND incident_type = $3 AND resolved_at IS NULL
RETURNING id, provider, model_alias, incident_type, status, window_seconds, opened_at, resolved_at, window_started_at, window_ended_at, sample_error, request_count, error_count, timeout_count, latency_p95_ms, metadata
`

type ResolveProviderIncidentParams struct {
	Provider     string `json:"provider"`
	ModelAlias   string `json:"model_alias"`
	IncidentType string `json:"incident_type"`
	Metadata     []byte `json:"metadata"`
}

func (q *Queries) ResolveProviderIncident(ctx context.Context, arg ResolveProviderIncidentParams) (ProviderIncident, error) {
	row := q.db.QueryRow(ctx, resolveProviderIncident,
		arg.Provider,
		arg.ModelAlias,
		arg.IncidentType,
		arg.Metadata,
	)
	var i ProviderIncident
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelAlias,
		&i.IncidentType,
		&i.Status,
		&i.WindowSeconds,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.WindowStartedAt,
		&i.WindowEndedAt,
		&i.SampleError,
		&i.RequestCount,
		&i.ErrorCount,
		&i.TimeoutCount,
		&i.LatencyP95Ms,
		&i.Metadata,
	)
	return i, err
}

const upsertProviderIncident = `-- name: UpsertProviderIncident :one
INSERT INTO provider_incidents (
    provider,
    model_alias,
    incident_type,
    status,
    window_seconds,
    opened_at,
    resolved_at,
    window_started_at,
    window_ended_at,
    sample_error,
    request_count,
    error_count,
    timeout_count,
    latency_p95_ms,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) ON CONFLICT (provider, model_alias, incident_type) WHERE resolved_at IS NULL
DO UPDATE SET
    status = EXCLUDED.status,
    window_seconds = EXCLUDED.window_seconds,
    opened_at = LEAST(provider_incidents.opened_at, EXCLUDED.opened_at),
    resolved_at = EXCLUDED.resolved_at,
    window_started_at = EXCLUDED.window_started_at,
    window_ended_at = EXCLUDED.window_ended_at,
    sample_error = COALESCE(EXCLUDED.sample_error, provider_incidents.sample_error),
    request_count = EXCLUDED.request_count,
    error_count = EXCLUDED.error_count,
    timeout_count = EXCLUDED.timeout_count,
    latency_p95_ms = EXCLUDED.latency_p95_ms,
    metadata = EXCLUDED.metadata
RETURNING id, provider, model_alias, incident_type, status, window_seconds, opened_at, resolved_at, window_started_at, window_ended_at, sample_error, request_count, error_count, timeout_count, latency_p95_ms, metadata
`

type UpsertProviderIncidentParams struct {
	Provider        string             `json:"provider"`
	ModelAlias      string             `json:"model_alias"`
	IncidentType    string             `json:"incident_type"`
	Status          string             `json:"status"`
	WindowSeconds   int32              `json:"window_seconds"`
	OpenedAt        pgtype.Timestamptz `json:"opened_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	WindowEndedAt   pgtype.Timestamptz `json:"window_ended_at"`
	SampleError     pgtype.Text        `json:"sample_error"`
	RequestCount    int32              `json:"request_count"`
	ErrorCount      int32              `json:"error_count"`
	TimeoutCount    int32              `json:"timeout_count"`
	LatencyP95Ms    pgtype.Int4        `json:"latency_p95_ms"`
	Metadata        []byte             `json:"metadata"`
}

func (q *Queries) UpsertProviderIncident(ctx context.Context, arg UpsertProviderIncidentParams) (ProviderIncident, error) {
	row := q.db.QueryRow(ctx, upsertProviderIncident,
		arg.Provider,
		arg.ModelAlias,
		arg.IncidentType,
		arg.Status,
		arg.WindowSeconds,
		arg.OpenedAt,
		arg.ResolvedAt,
		arg.WindowStartedAt,
		arg.WindowEndedAt,
		arg.SampleError,
		arg.RequestCount,
		arg.ErrorCount,
		arg.TimeoutCount,
		arg.LatencyP95Ms,
		arg.Metadata,
	)
	var i ProviderIncident
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelAlias,
		&i.IncidentType,
		&i.Status,
		&i.WindowSeconds,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.WindowStartedAt,
		&i.WindowEndedAt,
		&i.SampleError,
		&i.RequestCount,
		&i.ErrorCount,
		&i.TimeoutCount,
		&i.LatencyP95Ms,
		&i.Metadata,
	)
	return i, err
}
