// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_limit_defaults.sql

package db

import (
	"context"
)

const getRateLimitDefaults = `-- name: GetRateLimitDefaults :one
SELECT id, requests_per_minute, tokens_per_minute, parallel_requests_key, parallel_requests_tenant, created_at, updated_at
FROM rate_limit_defaults
WHERE id IS TRUE
`

func (q *Queries) GetRateLimitDefaults(ctx context.Context) (RateLimitDefault, error) {
	row := q.db.QueryRow(ctx, getRateLimitDefaults)
	var i RateLimitDefault
	err := row.Scan(
		&i.ID,
		&i.RequestsPerMinute,
		&i.TokensPerMinute,
		&i.ParallelRequestsKey,
		&i.ParallelRequestsTenant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRateLimitDefaults = `-- name: UpsertRateLimitDefaults :one
INSERT INTO rate_limit_defaults (
    id,
    requests_per_minute,
    tokens_per_minute,
    parallel_requests_key,
    parallel_requests_tenant
)
VALUES (TRUE, $1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
    SET requests_per_minute = EXCLUDED.requests_per_minute,
        tokens_per_minute = EXCLUDED.tokens_per_minute,
        parallel_requests_key = EXCLUDED.parallel_requests_key,
        parallel_requests_tenant = EXCLUDED.parallel_requests_tenant,
        updated_at = NOW()
RETURNING id, requests_per_minute, tokens_per_minute, parallel_requests_key, parallel_requests_tenant, created_at, updated_at
`

type UpsertRateLimitDefaultsParams struct {
	RequestsPerMinute      int32 `json:"requests_per_minute"`
	TokensPerMinute        int32 `json:"tokens_per_minute"`
	ParallelRequestsKey    int32 `json:"parallel_requests_key"`
	ParallelRequestsTenant int32 `json:"parallel_requests_tenant"`
}

func (q *Queries) UpsertRateLimitDefaults(ctx context.Context, arg UpsertRateLimitDefaultsParams) (RateLimitDefault, error) {
	row := q.db.QueryRow(ctx, upsertRateLimitDefaults,
		arg.RequestsPerMinute,
		arg.TokensPerMinute,
		arg.ParallelRequestsKey,
		arg.ParallelRequestsTenant,
	)
	var i RateLimitDefault
	err := row.Scan(
		&i.ID,
		&i.RequestsPerMinute,
		&i.TokensPerMinute,
		&i.ParallelRequestsKey,
		&i.ParallelRequestsTenant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
