// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responses_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertResponseCache = `-- name: InsertResponseCache :exec
INSERT INTO responses_cache (id, tenant_id, model, input, output, instructions, metadata, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertResponseCacheParams struct {
	ID           string             `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Model        string             `json:"model"`
	Input        []byte             `json:"input"`
	Output       []byte             `json:"output"`
	Instructions pgtype.Text        `json:"instructions"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertResponseCache(ctx context.Context, arg InsertResponseCacheParams) error {
	_, err := q.db.Exec(ctx, insertResponseCache,
		arg.ID,
		arg.TenantID,
		arg.Model,
		arg.Input,
		arg.Output,
		arg.Instructions,
		arg.Metadata,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getResponseCache = `-- name: GetResponseCache :one
SELECT id, tenant_id, model, input, output, instructions, metadata, created_at
FROM responses_cache
WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetResponseCache(ctx context.Context, id string) (ResponsesCache, error) {
	row := q.db.QueryRow(ctx, getResponseCache, id)
	var i ResponsesCache
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Model,
		&i.Input,
		&i.Output,
		&i.Instructions,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredResponseCache = `-- name: DeleteExpiredResponseCache :exec
DELETE FROM responses_cache WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredResponseCache(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredResponseCache)
	return err
}
