// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, updated_at, updated_by
FROM system_settings
WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (key, value, updated_at, updated_by)
VALUES ($1, $2, now(), $3)
ON CONFLICT (key)
DO UPDATE SET value = EXCLUDED.value, updated_at = now(), updated_by = EXCLUDED.updated_by
RETURNING key, value, updated_at, updated_by
`

type UpsertSystemSettingParams struct {
	Key       string      `json:"key"`
	Value     []byte      `json:"value"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.Key, arg.Value, arg.UpdatedBy)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
