// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_models.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTenantModel = `-- name: DeleteTenantModel :exec
DELETE FROM tenant_models
WHERE tenant_id = $1 AND alias = $2
`

type DeleteTenantModelParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Alias    string      `json:"alias"`
}

func (q *Queries) DeleteTenantModel(ctx context.Context, arg DeleteTenantModelParams) error {
	_, err := q.db.Exec(ctx, deleteTenantModel, arg.TenantID, arg.Alias)
	return err
}

const deleteTenantModels = `-- name: DeleteTenantModels :exec
DELETE FROM tenant_models
WHERE tenant_id = $1
`

func (q *Queries) DeleteTenantModels(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantModels, tenantID)
	return err
}

const insertTenantModel = `-- name: InsertTenantModel :exec
INSERT INTO tenant_models (tenant_id, alias)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertTenantModelParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Alias    string      `json:"alias"`
}

func (q *Queries) InsertTenantModel(ctx context.Context, arg InsertTenantModelParams) error {
	_, err := q.db.Exec(ctx, insertTenantModel, arg.TenantID, arg.Alias)
	return err
}

const listAllTenantModels = `-- name: ListAllTenantModels :many
SELECT tenant_id, alias
FROM tenant_models
`

type ListAllTenantModelsRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Alias    string      `json:"alias"`
}

func (q *Queries) ListAllTenantModels(ctx context.Context) ([]ListAllTenantModelsRow, error) {
	rows, err := q.db.Query(ctx, listAllTenantModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTenantModelsRow{}
	for rows.Next() {
		var i ListAllTenantModelsRow
		if err := rows.Scan(&i.TenantID, &i.Alias); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantModels = `-- name: ListTenantModels :many
SELECT alias
FROM tenant_models
WHERE tenant_id = $1
ORDER BY alias
`

func (q *Queries) ListTenantModels(ctx context.Context, tenantID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listTenantModels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var alias string
		if err := rows.Scan(&alias); err != nil {
			return nil, err
		}
		items = append(items, alias)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
