// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_exports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateUsageByModelForTenant = `-- name: AggregateUsageByModelForTenant :many
SELECT
    model_alias,
    provider,
    COALESCE(SUM(requests), 0)::bigint AS requests,
    COALESCE(SUM(input_tokens + output_tokens), 0)::bigint AS tokens,
    COALESCE(SUM(cost_cents), 0)::bigint AS cost_cents,
    COALESCE(SUM(cost_usd_micros), 0)::bigint AS cost_usd_micros
FROM usage_records
WHERE tenant_id = $1
  AND ts >= $2
  AND ts < $3
GROUP BY model_alias, provider
ORDER BY cost_usd_micros DESC, requests DESC
LIMIT $4
`

type AggregateUsageByModelForTenantParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Ts       pgtype.Timestamptz `json:"ts"`
	Ts_2     pgtype.Timestamptz `json:"ts_2"`
	Limit    int32              `json:"limit"`
}

type AggregateUsageByModelForTenantRow struct {
	ModelAlias    string `json:"model_alias"`
	Provider      string `json:"provider"`
	Requests      int64  `json:"requests"`
	Tokens        int64  `json:"tokens"`
	CostCents     int64  `json:"cost_cents"`
	CostUsdMicros int64  `json:"cost_usd_micros"`
}

func (q *Queries) AggregateUsageByModelForTenant(ctx context.Context, arg AggregateUsageByModelForTenantParams) ([]AggregateUsageByModelForTenantRow, error) {
	rows, err := q.db.Query(ctx, aggregateUsageByModelForTenant,
		arg.TenantID,
		arg.Ts,
		arg.Ts_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateUsageByModelForTenantRow{}
	for rows.Next() {
		var i AggregateUsageByModelForTenantRow
		if err := rows.Scan(
			&i.ModelAlias,
			&i.Provider,
			&i.Requests,
			&i.Tokens,
			&i.CostCents,
			&i.CostUsdMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimUsageExport = `-- name: ClaimUsageExport :one
UPDATE usage_exports
SET status = 'processing',
    started_at = NOW(),
    updated_at = NOW()
WHERE id = (
    SELECT id
    FROM usage_exports
    WHERE status = 'queued'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, scope, status, format, granularity, timezone, period_start, period_end, tenant_ids, requested_by, file_id, file_tenant_id, row_count, error, created_at, updated_at, started_at, completed_at
`

func (q *Queries) ClaimUsageExport(ctx context.Context) (UsageExport, error) {
	row := q.db.QueryRow(ctx, claimUsageExport)
	var i UsageExport
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Status,
		&i.Format,
		&i.Granularity,
		&i.Timezone,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TenantIds,
		&i.RequestedBy,
		&i.FileID,
		&i.FileTenantID,
		&i.RowCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeUsageExport = `-- name: CompleteUsageExport :one
UPDATE usage_exports
SET status = 'ready',
    file_id = $2,
    row_count = $3,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, scope, status, format, granularity, timezone, period_start, period_end, tenant_ids, requested_by, file_id, file_tenant_id, row_count, error, created_at, updated_at, started_at, completed_at
`

type CompleteUsageExportParams struct {
	ID       pgtype.UUID `json:"id"`
	FileID   pgtype.UUID `json:"file_id"`
	RowCount pgtype.Int4 `json:"row_count"`
}

func (q *Queries) CompleteUsageExport(ctx context.Context, arg CompleteUsageExportParams) (UsageExport, error) {
	row := q.db.QueryRow(ctx, completeUsageExport, arg.ID, arg.FileID, arg.RowCount)
	var i UsageExport
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Status,
		&i.Format,
		&i.Granularity,
		&i.Timezone,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TenantIds,
		&i.RequestedBy,
		&i.FileID,
		&i.FileTenantID,
		&i.RowCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createUsageExport = `-- name: CreateUsageExport :one
INSERT INTO usage_exports (
    scope,
    status,
    format,
    granularity,
    timezone,
    period_start,
    period_end,
    tenant_ids,
    requested_by,
    file_tenant_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, scope, status, format, granularity, timezone, period_start, period_end, tenant_ids, requested_by, file_id, file_tenant_id, row_count, error, created_at, updated_at, started_at, completed_at
`

type CreateUsageExportParams struct {
	Scope        string             `json:"scope"`
	Status       string             `json:"status"`
	Format       string             `json:"format"`
	Granularity  string             `json:"granularity"`
	Timezone     string             `json:"timezone"`
	PeriodStart  pgtype.Timestamptz `json:"period_start"`
	PeriodEnd    pgtype.Timestamptz `json:"period_end"`
	TenantIds    []pgtype.UUID      `json:"tenant_ids"`
	RequestedBy  pgtype.UUID        `json:"requested_by"`
	FileTenantID pgtype.UUID        `json:"file_tenant_id"`
}

func (q *Queries) CreateUsageExport(ctx context.Context, arg CreateUsageExportParams) (UsageExport, error) {
	row := q.db.QueryRow(ctx, createUsageExport,
		arg.Scope,
		arg.Status,
		arg.Format,
		arg.Granularity,
		arg.Timezone,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TenantIds,
		arg.RequestedBy,
		arg.FileTenantID,
	)
	var i UsageExport
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Status,
		&i.Format,
		&i.Granularity,
		&i.Timezone,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TenantIds,
		&i.RequestedBy,
		&i.FileID,
		&i.FileTenantID,
		&i.RowCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const exportUsageRows = `-- name: ExportUsageRows :many
SELECT
    timezone($5::text, date_trunc($4::text, u.ts AT TIME ZONE $5::text))::timestamptz AS bucket,
    u.tenant_id,
    t.name AS tenant_name,
    u.model_alias,
    u.provider,
    COALESCE(SUM(u.requests), 0)::bigint AS requests,
    COALESCE(SUM(u.input_tokens), 0)::bigint AS input_tokens,
    COALESCE(SUM(u.output_tokens), 0)::bigint AS output_tokens,
    COALESCE(SUM(u.cost_cents), 0)::bigint AS cost_cents,
    COALESCE(SUM(u.cost_usd_micros), 0)::bigint AS cost_usd_micros
FROM usage_records u
JOIN tenants t ON t.id = u.tenant_id
WHERE u.ts >= $1
  AND u.ts < $2
  AND ($3::uuid[] IS NULL OR u.tenant_id = ANY($3::uuid[]))
GROUP BY bucket, u.tenant_id, t.name, u.model_alias, u.provider
ORDER BY bucket, t.name, u.model_alias
`

type ExportUsageRowsParams struct {
	Ts      pgtype.Timestamptz `json:"ts"`
	Ts_2    pgtype.Timestamptz `json:"ts_2"`
	Column3 []pgtype.UUID      `json:"column_3"`
	Column4 string             `json:"column_4"`
	Column5 string             `json:"column_5"`
}

type ExportUsageRowsRow struct {
	Bucket        pgtype.Timestamptz `json:"bucket"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	TenantName    string             `json:"tenant_name"`
	ModelAlias    string             `json:"model_alias"`
	Provider      string             `json:"provider"`
	Requests      int64              `json:"requests"`
	InputTokens   int64              `json:"input_tokens"`
	OutputTokens  int64              `json:"output_tokens"`
	CostCents     int64              `json:"cost_cents"`
	CostUsdMicros int64              `json:"cost_usd_micros"`
}

func (q *Queries) ExportUsageRows(ctx context.Context, arg ExportUsageRowsParams) ([]ExportUsageRowsRow, error) {
	rows, err := q.db.Query(ctx, exportUsageRows,
		arg.Ts,
		arg.Ts_2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportUsageRowsRow{}
	for rows.Next() {
		var i ExportUsageRowsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.TenantID,
			&i.TenantName,
			&i.ModelAlias,
			&i.Provider,
			&i.Requests,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostCents,
			&i.CostUsdMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failUsageExport = `-- name: FailUsageExport :one
UPDATE usage_exports
SET status = 'failed',
    error = $2,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, scope, status, format, granularity, timezone, period_start, period_end, tenant_ids, requested_by, file_id, file_tenant_id, row_count, error, created_at, updated_at, started_at, completed_at
`

type FailUsageExportParams struct {
	ID    pgtype.UUID `json:"id"`
	Error pgtype.Text `json:"error"`
}

func (q *Queries) FailUsageExport(ctx context.Context, arg FailUsageExportParams) (UsageExport, error) {
	row := q.db.QueryRow(ctx, failUsageExport, arg.ID, arg.Error)
	var i UsageExport
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Status,
		&i.Format,
		&i.Granularity,
		&i.Timezone,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TenantIds,
		&i.RequestedBy,
		&i.FileID,
		&i.FileTenantID,
		&i.RowCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUsageExport = `-- name: GetUsageExport :one
SELECT id, scope, status, format, granularity, timezone, period_start, period_end, tenant_ids, requested_by, file_id, file_tenant_id, row_count, error, created_at, updated_at, started_at, completed_at
FROM usage_exports
WHERE id = $1
`

func (q *Queries) GetUsageExport(ctx context.Context, id pgtype.UUID) (UsageExport, error) {
	row := q.db.QueryRow(ctx, getUsageExport, id)
	var i UsageExport
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Status,
		&i.Format,
		&i.Granularity,
		&i.Timezone,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TenantIds,
		&i.RequestedBy,
		&i.FileID,
		&i.FileTenantID,
		&i.RowCount,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listUsageExportsAdmin = `-- name: ListUsageExportsAdmin :many
SELECT id, scope, status, format, granularity, timezone, period_start, period_end, tenant_ids, requested_by, file_id, file_tenant_id, row_count, error, created_at, updated_at, started_at, completed_at
FROM usage_exports
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsageExportsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsageExportsAdmin(ctx context.Context, arg ListUsageExportsAdminParams) ([]UsageExport, error) {
	rows, err := q.db.Query(ctx, listUsageExportsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageExport{}
	for rows.Next() {
		var i UsageExport
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Status,
			&i.Format,
			&i.Granularity,
			&i.Timezone,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TenantIds,
			&i.RequestedBy,
			&i.FileID,
			&i.FileTenantID,
			&i.RowCount,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageExportsByRequester = `-- name: ListUsageExportsByRequester :many
SELECT id, scope, status, format, granularity, timezone, period_start, period_end, tenant_ids, requested_by, file_id, file_tenant_id, row_count, error, created_at, updated_at, started_at, completed_at
FROM usage_exports
WHERE requested_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsageExportsByRequesterParams struct {
	RequestedBy pgtype.UUID `json:"requested_by"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListUsageExportsByRequester(ctx context.Context, arg ListUsageExportsByRequesterParams) ([]UsageExport, error) {
	rows, err := q.db.Query(ctx, listUsageExportsByRequester, arg.RequestedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageExport{}
	for rows.Next() {
		var i UsageExport
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Status,
			&i.Format,
			&i.Granularity,
			&i.Timezone,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.TenantIds,
			&i.RequestedBy,
			&i.FileID,
			&i.FileTenantID,
			&i.RowCount,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
