// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name)
VALUES ($1, $2)
RETURNING id, email, name, is_super_admin, personal_tenant_id, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.PersonalTenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, is_super_admin, personal_tenant_id, created_at, updated_at, last_login_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.PersonalTenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, is_super_admin, personal_tenant_id, created_at, updated_at, last_login_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.PersonalTenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, is_super_admin, personal_tenant_id, created_at, updated_at, last_login_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsSuperAdmin,
			&i.PersonalTenantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, email, name
FROM users
WHERE id = ANY($1::uuid[])
`

type ListUsersByIDsRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) ListUsersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByIDsRow{}
	for rows.Next() {
		var i ListUsersByIDsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSuperAdmin = `-- name: SetUserSuperAdmin :exec
UPDATE users
SET is_super_admin = $2,
    updated_at = NOW()
WHERE id = $1
`

type SetUserSuperAdminParams struct {
	ID           pgtype.UUID `json:"id"`
	IsSuperAdmin bool        `json:"is_super_admin"`
}

func (q *Queries) SetUserSuperAdmin(ctx context.Context, arg SetUserSuperAdminParams) error {
	_, err := q.db.Exec(ctx, setUserSuperAdmin, arg.ID, arg.IsSuperAdmin)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPersonalTenant = `-- name: UpdateUserPersonalTenant :one
UPDATE users
SET personal_tenant_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, is_super_admin, personal_tenant_id, created_at, updated_at, last_login_at
`

type UpdateUserPersonalTenantParams struct {
	ID               pgtype.UUID `json:"id"`
	PersonalTenantID pgtype.UUID `json:"personal_tenant_id"`
}

func (q *Queries) UpdateUserPersonalTenant(ctx context.Context, arg UpdateUserPersonalTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPersonalTenant, arg.ID, arg.PersonalTenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.PersonalTenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, is_super_admin, personal_tenant_id, created_at, updated_at, last_login_at
`

type UpdateUserProfileParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.IsSuperAdmin,
		&i.PersonalTenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
